name: Update README with GitHub Stats

on:
  schedule:
    # Planification toutes les 4 jours à minuit UTC
    - cron: '0 0 */4 * *'  # Tous les 4 jours à 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Mettre à jour le README sans duplication
      - name: Update README with stats
        run: |
          # Télécharger le README actuel
          curl -o README.md "https://raw.githubusercontent.com/enokseth/enokseth/main/README.md"

          # Utiliser sed pour nettoyer et remplacer le contenu
          sed -i '/## GitHub Statistiques/,$d' README.md

          # Ajouter les nouvelles sections de statistiques sans doublon
          {
            echo "## GitHub Statistiques"
            echo "![Statistiques GitHub](https://github-readme-stats.vercel.app/api?username=enokseth&show_icons=true&count_private=true)"
            echo "## Programming languages"
            echo "![Langages de programmation](https://github-readme-stats.vercel.app/api/top-langs/?username=enokseth&layout=compact&count_private=true)"
          } >> README.md

      # Commit et push des modifications
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
