name: Update README with GitHub Stats

on:
  schedule:
    # Planification (ajuste la fréquence si nécessaire)
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Récupérer les statistiques et générer le README
      - name: Generate README with stats
        run: |
          curl -o README.md "https://raw.githubusercontent.com/enokseth/enokseth/main/README.md"
          echo "\n## GitHub Statistiques" >> README.md
          echo "![Statistiques GitHub](https://github-readme-stats.vercel.app/api?username=enokseth&show_icons=true&count_private=true)" >> README.md
          echo "\n## Programming languages" >> README.md
          echo "![Langages de programmation](https://github-readme-stats.vercel.app/api/top-langs/?username=enokseth&layout=compact&count_private=true)" >> README.md

      # Commit et push des modifications
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
